### ISSUE TITLE
Error: Cannot resolve module 'jquery' 

### ISSUE THREAD

**Issue by leesx** [yy-chaok/practices#17]
ERROR in ./ucjs_modules/jquery-daterangepicker/1.0.0/jquery-daterangepicker.js
Module not found: Error: Cannot resolve module 'jquery' in D:\WWW\leesx00\ucjs_modules\jquery-daterangepicker\1.0.0
 @ ./ucjs_modules/jquery-daterangepicker/1.0.0/jquery-daterangepicker.js 13:8-45

**Comment by xpcode** [comment]
windows平台下的编译问题，已解决 https://github.com/yy-chaok/practices/pull/19
