### ISSUE TITLE
error:_DevTools2.default.instrument is not a function

### ISSUE THREAD

**Issue by fuwenfang** [yy-chaok/practices#4]
If the Google browser does not install DevTools Redux,After running node server/,There will be an error in the console platform.The wrong content is:_DevTools2.default.instrument is not a function.

**Comment by xpcode** [comment]
Redux DevTools

https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en-US

**Comment by xpcode** [comment]
#5 fixed
